### ISSUE TITLE
Could we have some instructions to run the app locally?

### ISSUE THREAD

**Issue by alecrem** [TheGameKnave/premodernoracle#11]
I ran `npm install` both on the root folder and on `client/`, but running `npm run dev` complains for the lack of an `.env`. The frontend is running, but the API returns HTTP 502.

It would be nice to have a sample `.env` file committed to the repo, as well as some instructions for people trying to run the project locally to be able to contribute some code.

(I can help with the instructions once I can run the project.)

**Comment by TheGameKnave** [comment]
Sorry about that. I'm used to .env containing sensitive information, but it doesn't on this project.
